-- =====================================================
-- SmartSchemes — Seed Data for Supabase
-- Run AFTER supabase_schema.sql in Supabase SQL Editor
-- =====================================================

-- ── Business Schemes ──────────────────────────────────
INSERT INTO business_schemes (name, description, min_age, max_age, min_income, max_income, business_type, min_investment, max_investment, states, benefits, eligibility, application_process, deadline, website, funding_amount, ministry, tags) VALUES

('Pradhan Mantri MUDRA Yojana (PMMY)',
 'Provides loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises. Three categories: Shishu (up to ₹50,000), Kishore (₹50,000 to ₹5 lakh), and Tarun (₹5 lakh to ₹10 lakh).',
 18, 65, 0, 1500000,
 ARRAY['startup','msme','retail','services','manufacturing'], 0, 1000000, ARRAY['all'],
 ARRAY['Collateral-free loans up to ₹10 lakh','Low interest rates','No processing fee','Flexible repayment tenure of 5-7 years','MUDRA Card for working capital needs'],
 ARRAY['Indian citizen aged 18-65','Non-corporate small business entity','Has a business plan or existing business','No previous loan default'],
 ARRAY['Visit nearest bank branch or NBFC','Fill MUDRA loan application form','Submit business plan and identity documents','Bank evaluates and sanctions loan','Loan disbursement within 7-10 working days'],
 'Ongoing', 'https://www.mudra.org.in', 'Up to ₹10 Lakh', 'Ministry of Finance',
 ARRAY['mudra','loan','small business','micro enterprise','collateral free']),

('Startup India Seed Fund Scheme (SISFS)',
 'Provides financial assistance to startups for proof of concept, prototype development, product trials, market entry, and commercialization through incubators.',
 21, 55, 0, 5000000,
 ARRAY['startup','technology'], 100000, 5000000, ARRAY['all'],
 ARRAY['Grants up to ₹20 lakh for validation of proof of concept','Loans up to ₹50 lakh for market launch','Mentorship and networking opportunities','Access to government tenders','Tax exemptions for 3 years'],
 ARRAY['DPIIT-recognized startup','Not more than 2 years old at time of application','Must have a technology-driven business model','Should not have received funding above ₹10 lakh from other government schemes'],
 ARRAY['Register on Startup India portal','Apply through an eligible incubator','Submit business plan and financials','Expert committee evaluation','Approval and fund disbursement through incubator'],
 'March 2026', 'https://seedfund.startupindia.gov.in', 'Up to ₹50 Lakh', 'DPIIT, Ministry of Commerce',
 ARRAY['startup','seed fund','innovation','technology','incubator']),

('PM Vishwakarma Yojana',
 'End-to-end support for traditional artisans and craftspeople through recognition, skill training, toolkit incentives, credit access, and market support.',
 18, 60, 0, 800000,
 ARRAY['manufacturing','services','retail'], 0, 300000, ARRAY['all'],
 ARRAY['Recognition through PM Vishwakarma certificate and ID card','Skill training: ₹500/day stipend for 5-7 days','Toolkit incentive up to ₹15,000','Collateral-free loan: ₹1 lakh (1st tranche), ₹2 lakh (2nd tranche) at 5% interest','Marketing support through GeM portal and trade fairs'],
 ARRAY['Traditional artisan or craftsperson','Working with hands and tools in one of 18 identified trades','Registered under PM Vishwakarma portal','Age 18 years and above'],
 ARRAY['Register at pmvishwakarma.gov.in','Verification by Gram Panchayat/ULB','Attend skill training program','Apply for toolkit incentive and credit','Access marketing platforms'],
 'Ongoing (5-year scheme)', 'https://pmvishwakarma.gov.in', 'Up to ₹3 Lakh loan + ₹15,000 toolkit', 'Ministry of MSME',
 ARRAY['artisan','craftspeople','skill','toolkit','traditional']),

('Stand-Up India Scheme',
 'Facilitates bank loans between ₹10 lakh and ₹1 crore for SC/ST and women entrepreneurs for greenfield enterprises in manufacturing, services, or trading.',
 18, 65, 0, 3000000,
 ARRAY['startup','msme','manufacturing','services','retail'], 1000000, 10000000, ARRAY['all'],
 ARRAY['Loans from ₹10 lakh to ₹1 crore','Composite loan covering term loan and working capital','Repayment period up to 7 years','Margin money of up to 25%','Rate of interest: lowest applicable rate + 3% + tenor premium'],
 ARRAY['SC/ST and/or women entrepreneurs','Age 18 years and above','Setting up greenfield enterprise','Non-individual enterprise should have 51% shareholding by SC/ST/woman','Borrower should not be in default to any bank/financial institution'],
 ARRAY['Visit www.standupmitra.in portal','Register and fill application','Connect with nearest bank branch','Submit project report and documents','Loan sanctioned within 30 days of application'],
 'Extended till 2025', 'https://www.standupmitra.in', '₹10 Lakh to ₹1 Crore', 'Ministry of Finance',
 ARRAY['women','sc','st','greenfield','bank loan']),

('Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)',
 'Provides collateral-free credit facility to micro and small enterprises. Covers both new and existing enterprises in manufacturing and service sectors.',
 18, 65, 0, 5000000,
 ARRAY['msme','manufacturing','services','startup'], 0, 5000000, ARRAY['all'],
 ARRAY['Collateral-free loans up to ₹5 crore','Cover up to 85% of the loan amount','Available for both new and existing MSEs','No third-party guarantee required','Lower effective cost of credit'],
 ARRAY['Micro or Small Enterprise as per MSME Act','Both new and existing enterprises eligible','Manufacturing or service sector','Should have a viable project/business'],
 ARRAY['Apply through any eligible lending institution','Submit business proposal with financials','Lending institution evaluates the proposal','If approved, guarantee cover obtained from CGTMSE','Loan disbursed without collateral'],
 'Ongoing', 'https://www.cgtmse.in', 'Up to ₹5 Crore', 'Ministry of MSME',
 ARRAY['collateral free','guarantee','msme','credit','small enterprise']),

('PM Kisan Samman Nidhi Yojana',
 'Direct income support of ₹6,000 per year to all farmer families across the country, paid in three equal installments every four months.',
 18, 75, 0, 600000,
 ARRAY['agriculture'], 0, 500000, ARRAY['all'],
 ARRAY['₹6,000 per year direct bank transfer','Three installments of ₹2,000 each','No intermediary — direct to farmer''s account','All landholding farmer families eligible','KCC integration for crop loans'],
 ARRAY['Small and marginal farmer family','Must own cultivable land','Should not hold constitutional post','Not a current or former minister/MP/MLA','Professional income should not exceed limit'],
 ARRAY['Visit local Common Service Centre (CSC)','Register at pmkisan.gov.in','Provide Aadhaar, bank details, and land records','State government verifies records','Amount credited directly to bank account'],
 'Ongoing', 'https://pmkisan.gov.in', '₹6,000/year', 'Ministry of Agriculture',
 ARRAY['farmer','kisan','direct benefit','agriculture','income support']),

('Atal Innovation Mission (AIM) - Atal Incubation Centres',
 'Establishes world-class incubation centres that foster innovation and entrepreneurship across India. Provides grant-in-aid up to ₹10 crore for establishing incubators.',
 21, 50, 0, 10000000,
 ARRAY['startup','technology'], 500000, 50000000, ARRAY['all'],
 ARRAY['Grant-in-aid up to ₹10 crore over 5 years','Access to mentors and industry experts','State-of-the-art infrastructure','Networking with global innovation ecosystem','Connect with angel investors and VCs'],
 ARRAY['Higher educational institutions or R&D institutes can apply','Corporate sector and alternative investment funds','Must have space and infrastructure readiness','Should demonstrate innovation focus'],
 ARRAY['Apply through AIM portal during open call','Submit detailed proposal with infrastructure plan','Expert committee evaluation','Site visit and due diligence','Grant disbursement in tranches'],
 'Periodic calls', 'https://aim.gov.in', 'Up to ₹10 Crore', 'NITI Aayog',
 ARRAY['innovation','incubation','atal','startup ecosystem','technology']),

('SIDBI Make in India Soft Loan Fund (SMILE)',
 'Provides soft loans to MSMEs for setting up new enterprises or expansion/modernization of existing units in the manufacturing sector.',
 21, 60, 0, 8000000,
 ARRAY['msme','manufacturing','startup'], 1000000, 25000000, ARRAY['all'],
 ARRAY['Soft loans up to ₹25 crore','Subsidized interest rates (around 2% lower than market)','Longer repayment period up to 10 years','Supports manufacturing modernization','Quick loan processing'],
 ARRAY['Registered MSME unit','Manufacturing sector focus','Viable business plan for expansion/new setup','Satisfactory credit history'],
 ARRAY['Apply through SIDBI portal or branch','Submit project report and financials','SIDBI evaluates the proposal','Terms sanctioned and agreed upon','Disbursement aligned with project milestones'],
 'Ongoing', 'https://www.sidbi.in', 'Up to ₹25 Crore', 'Ministry of Finance (SIDBI)',
 ARRAY['sidbi','soft loan','make in india','manufacturing','expansion']),

('Agriculture Infrastructure Fund (AIF)',
 'Financing facility for creating post-harvest management infrastructure and community farming assets, with interest subvention and credit guarantee support.',
 18, 70, 0, 2000000,
 ARRAY['agriculture'], 100000, 20000000, ARRAY['all'],
 ARRAY['Loans up to ₹2 crore with 3% interest subvention for 7 years','Credit guarantee coverage under CGTMSE','Moratorium for repayment','Covers warehouses, cold storage, grading/sorting units','FPOs and agri-entrepreneurs eligible'],
 ARRAY['Farmers, FPOs, PACS, Marketing Cooperative Societies','Agri-entrepreneurs, Startups','State agencies and APMCs','Project should be viable and contribute to agri infrastructure'],
 ARRAY['Register on AIF portal (agriinfra.dac.gov.in)','Select project type and fill details','Choose lending bank','Bank evaluates and sanctions loan','Interest subvention applied automatically'],
 'Until 2025-26', 'https://agriinfra.dac.gov.in', 'Up to ₹2 Crore with interest subvention', 'Ministry of Agriculture',
 ARRAY['agriculture','infrastructure','cold storage','warehouse','FPO']),

('Export Promotion Capital Goods (EPCG) Scheme',
 'Allows import of capital goods at zero customs duty for export production, subject to export obligation of 6 times the duty saved over 6 years.',
 21, 65, 500000, 100000000,
 ARRAY['export','manufacturing'], 5000000, 100000000, ARRAY['all'],
 ARRAY['Zero customs duty on capital goods imports','Applicable on new and second-hand capital goods','Boost manufacturing competitiveness','6-year export obligation period','Technology upgradation support'],
 ARRAY['Manufacturer exporter or merchant exporter','EOU/SEZ unit or status holder','Must commit to export obligations','Valid IEC (Import Export Code) required'],
 ARRAY['Apply online through DGFT portal','Submit application with EPCG authorization','Import capital goods at zero duty','Fulfill export obligation within 6 years','Submit export evidence for obligation redemption'],
 'Ongoing', 'https://www.dgft.gov.in', 'Zero customs duty on capital goods', 'Ministry of Commerce',
 ARRAY['export','capital goods','customs','manufacturing','international trade']);


-- ── Education Schemes ─────────────────────────────────
INSERT INTO education_schemes (name, description, min_age, max_age, education_level, category, min_income, max_income, field_of_study, states, benefits, eligibility, application_process, deadline, website, scholarship_amount, ministry, tags) VALUES

('PM Vidyalaxmi Scheme',
 'Provides collateral-free, guarantor-free educational loans for students admitted to top quality higher education institutions. Financial support covers full tuition and related expenses.',
 17, 30, ARRAY['ug','pg','diploma'], ARRAY['all'], 0, 800000, ARRAY['all'], ARRAY['all'],
 ARRAY['Collateral-free education loans up to ₹10 lakh','Interest subvention of 3% during moratorium period','Full tuition fee coverage','75% government credit risk guarantee','Simple digital application process'],
 ARRAY['Admitted to NIRF top-ranked institutions','NAAC A+ graded institutions','Annual family income up to ₹8 lakh for interest subvention','Indian citizen','First-time higher education loan'],
 ARRAY['Visit pmvidyalaxmi.gov.in portal','Register with academic and personal details','Select institution and course','Apply to multiple banks through unified platform','Loan processed within 15 working days'],
 'Ongoing', 'https://pmvidyalaxmi.gov.in', 'Loan up to ₹10 Lakh + 3% interest subvention', 'Ministry of Education',
 ARRAY['education loan','collateral free','higher education','vidyalaxmi']),

('National Scholarship Portal (NSP) - Central Sector Scheme',
 'Scholarship for students from non-creamy layer families studying in colleges/universities. Merit-based scholarship for UG and PG students across India.',
 16, 25, ARRAY['ug','pg'], ARRAY['all'], 0, 800000, ARRAY['all'], ARRAY['all'],
 ARRAY['₹12,000/year for UG students (first 3 years)','₹20,000/year for PG students','Direct transfer to bank account','Covers tuition and maintenance','Renewable annually on performance'],
 ARRAY['Must be in top 20 percentile of board exam','Family income below ₹8 lakh per annum','Regular student in recognized institution','Must maintain 50% attendance','Indian nationality'],
 ARRAY['Register on scholarships.gov.in','Fill application with academic details','Upload required documents','Institute verification','Scholarship disbursed after final verification'],
 'October - December annually', 'https://scholarships.gov.in', '₹12,000 - ₹20,000 per year', 'Ministry of Education',
 ARRAY['scholarship','merit','central','undergraduate','postgraduate']),

('Post-Matric Scholarship for SC Students',
 'Central government scholarship for Scheduled Caste students pursuing post-matriculation or post-secondary education. Covers maintenance allowance and non-refundable fees.',
 15, 35, ARRAY['school','ug','pg','phd','diploma'], ARRAY['sc'], 0, 250000, ARRAY['all'], ARRAY['all'],
 ARRAY['Full tuition fee reimbursement','Monthly maintenance allowance (₹550-₹1,200 depending on level)','Reader charges for blind students','Study tour charges','Thesis typing and printing charges for research scholars'],
 ARRAY['Belongs to Scheduled Caste category','Family income not exceeding ₹2.5 lakh per annum','Studying in recognized institution','Must have passed qualifying exam','Not receiving any other scholarship'],
 ARRAY['Apply through National Scholarship Portal','Upload caste certificate and income proof','Submit fee receipt from institution','Institute forwards verified application','State government approves and disburses'],
 'August - November annually', 'https://scholarships.gov.in', 'Full tuition + ₹550-₹1,200/month maintenance', 'Ministry of Social Justice & Empowerment',
 ARRAY['sc','post-matric','scheduled caste','maintenance','tuition']),

('INSPIRE Scholarship (SHE - Scholarship for Higher Education)',
 'Scholarship for meritorious students to study natural and basic sciences at BSc and MSc levels. Part of the Innovation in Science Pursuit for Inspired Research (INSPIRE) programme.',
 17, 27, ARRAY['ug','pg'], ARRAY['all'], 0, 10000000, ARRAY['science','mathematics','engineering'], ARRAY['all'],
 ARRAY['₹80,000 per year scholarship','₹20,000 summer research project mentorship','Exposure to scientific research environment','5-year support (BSc + MSc)','No income criteria — purely merit-based'],
 ARRAY['Top 1% in Class 12 board exams','JEE/NEET qualified students','KVPY/Olympiad medal winners','Pursuing BSc/BS/Int. MSc in natural/basic sciences','Studying in recognized Indian institution'],
 ARRAY['Apply online at www.online-inspire.gov.in','Upload Class 12 marksheet and admit card','Select institution and course','Verification by DST-INSPIRE team','Scholarship disbursed annually'],
 'September - November annually', 'https://online-inspire.gov.in', '₹80,000/year + ₹20,000 mentorship', 'Department of Science & Technology',
 ARRAY['science','inspire','research','merit','basic sciences']),

('Prime Minister''s Special Scholarship Scheme (PMSSS) for J&K and Ladakh',
 'Scholarship for students from Jammu & Kashmir and Ladakh to pursue undergraduate courses in colleges and universities outside the UT.',
 17, 25, ARRAY['ug'], ARRAY['all'], 0, 800000, ARRAY['all'], ARRAY['jammu & kashmir','ladakh'],
 ARRAY['Academic fee up to ₹3 lakh/year (engineering) or ₹2 lakh (other courses)','Maintenance allowance of ₹1 lakh/year','Support for 5,000 students annually','Covers professional and general degree courses','Hostel/accommodation support'],
 ARRAY['Domicile of J&K or Ladakh','Passed 10+2 from J&K/Ladakh board or CBSE school in UT','Family income below ₹8 lakh per annum','Admitted to approved institution outside J&K/Ladakh','Not availing any other central scholarship'],
 ARRAY['Register on AICTE PMSSS portal','Fill application and upload documents','Participate in counselling rounds','Get allotted institution and confirm admission','Scholarship disbursed after joining'],
 'April - June annually', 'https://www.aicte-india.org/pmsss', 'Up to ₹3 Lakh tuition + ₹1 Lakh maintenance', 'AICTE / Ministry of Education',
 ARRAY['jammu kashmir','ladakh','pmsss','undergraduate','special area']),

('Maulana Azad National Fellowship (MANF)',
 'Fellowship for minority community students pursuing M.Phil and Ph.D. Provides financial assistance for research scholars from six notified minority communities.',
 20, 40, ARRAY['pg','phd'], ARRAY['minority'], 0, 600000, ARRAY['all'], ARRAY['all'],
 ARRAY['₹31,000/month for JRF (first 2 years)','₹35,000/month for SRF (remaining tenure)','HRA as per university norms','₹10,000/year contingency for humanities','₹20,500/year contingency for sciences'],
 ARRAY['Belongs to minority community (Muslim, Christian, Sikh, Buddhist, Jain, Parsi)','Admitted to M.Phil/Ph.D in recognized university','Qualified UGC-NET/JRF or university entrance test','Family income not exceeding ₹6 lakh per annum'],
 ARRAY['Apply through UGC portal during open call','Submit minority community certificate','Upload NET/JRF qualification and admission proof','UGC evaluates and selects candidates','Fellowship disbursed monthly through institution'],
 'January - March annually', 'https://www.ugc.ac.in', '₹31,000-₹35,000/month + HRA', 'University Grants Commission',
 ARRAY['minority','fellowship','phd','mphil','research','maulana azad']),

('Pragati Scholarship for Girl Students (AICTE)',
 'AICTE scholarship scheme for girl students admitted to first year of degree/diploma in AICTE approved institutions to promote women''s participation in technical education.',
 17, 25, ARRAY['ug','diploma'], ARRAY['all'], 0, 800000, ARRAY['engineering','technology','architecture','pharmacy'], ARRAY['all'],
 ARRAY['₹50,000 per year scholarship','Up to ₹2,000/month (10 months) for incidentals','4-year support for degree courses','3-year support for diploma courses','Directly credited to student''s bank account'],
 ARRAY['Girl student admitted to 1st year degree/diploma','AICTE approved institution','Family income not exceeding ₹8 lakh per annum','Only two girl children per family eligible','Must have 75% attendance'],
 ARRAY['Apply through National Scholarship Portal (NSP)','Fill in academic and personal details','Upload all required documents','Verification by institute and state','Scholarship credited after final approval'],
 'October - December annually', 'https://www.aicte-india.org', '₹50,000 per year', 'AICTE',
 ARRAY['girl student','women','technical education','aicte','pragati']),

('Pre-Matric Scholarship for OBC Students',
 'Scholarship for OBC students studying in classes 1 to 10 to support their education and prevent dropouts. Government of India centrally-sponsored scheme.',
 6, 18, ARRAY['school'], ARRAY['obc'], 0, 250000, ARRAY['all'], ARRAY['all'],
 ARRAY['₹25-₹100/month maintenance allowance (10 months)','Ad-hoc grant for books and stationery','Hostel maintenance for hostellers','Covers Class 1 to 10 students','Renewable annually on passing'],
 ARRAY['Belongs to OBC category','Family income not exceeding ₹2.5 lakh per annum','Studying in government or recognized school','Must have passed previous exam','Not receiving any other pre-matric scholarship'],
 ARRAY['Apply through National Scholarship Portal','Upload OBC certificate, income proof','Submit school admission and fee receipt','Institute verification','Disbursed through state government'],
 'August - October annually', 'https://scholarships.gov.in', '₹25-₹100/month + book grant', 'Ministry of Social Justice & Empowerment',
 ARRAY['obc','pre-matric','school','maintenance','dropout prevention']),

('Ishan Uday – Special Scholarship for NE Region',
 'UGC scholarship for students from North Eastern states pursuing general degree courses in colleges/universities away from their home state.',
 17, 25, ARRAY['ug'], ARRAY['all'], 0, 450000, ARRAY['all'], ARRAY['assam','arunachal pradesh','manipur','meghalaya','mizoram','nagaland','sikkim','tripura'],
 ARRAY['₹5,400/month for general degree courses','₹7,800/month for technical/professional courses','10-month annual support','10,000 fresh scholarships annually','Study support outside home state'],
 ARRAY['Domicile of North Eastern state','Passed 12th from NE state institution','Family income not exceeding ₹4.5 lakh per annum','Admitted to recognized institution','Not availing any other UGC scholarship'],
 ARRAY['Apply through National Scholarship Portal (NSP)','Upload domicile certificate and 12th marksheet','Submit admission letter and income proof','UGC verification process','Scholarship disbursed through DBT'],
 'October - December annually', 'https://scholarships.gov.in', '₹5,400 - ₹7,800/month', 'University Grants Commission',
 ARRAY['northeast','ne region','ishan uday','undergraduate','special area']),

('National Means-cum-Merit Scholarship Scheme (NMMSS)',
 'Provides scholarships to meritorious students from economically weaker sections to reduce dropout rate at Class 8 and encourage continuation to secondary/higher secondary.',
 12, 18, ARRAY['school'], ARRAY['all'], 0, 350000, ARRAY['all'], ARRAY['all'],
 ARRAY['₹12,000 per year (₹1,000/month)','Support from Class 9 to Class 12','Directly to student''s bank account','1 lakh scholarships awarded nationally each year','Renewable based on promotion to next class'],
 ARRAY['Studying in Class 8 in government/aided school','Minimum 55% marks in Class 7','Family income below ₹3.5 lakh per annum','Must qualify NMMS examination (MAT + SAT)','Should be studying in state government/aided school'],
 ARRAY['Register through National Scholarship Portal','Appear for NMMS exam conducted by state','Submit result and qualifying documents','State SNA verifies and selects candidates','Scholarship disbursed from Class 9 onwards'],
 'August - November annually', 'https://scholarships.gov.in', '₹12,000/year', 'Ministry of Education',
 ARRAY['merit','means','school','dropout prevention','class 8 to 12']);
